language: node_js
node_js: '8'
cache: yarn
git:
  depth: 3
addons:
  ssh_known_hosts:
  - dev.oked.me
before_install:
- openssl aes-256-cbc -K $encrypted_f3d159b64582_key -iv $encrypted_f3d159b64582_iv
  -in deploy.tar.enc -out deploy.tar -d
- tar xvf deploy.tar
- rm deploy.tar.enc
- chmod 600 deploy-key
- chmod 700 deploy-script.sh
- mkdir dist
- cp package.json ./dist/
install:
- yarn
script:
- yarn build
after_success:
- "./deploy-script.sh"
